Spectral Integral Suite in C++: test/3DOldroydBDesHalfStress.cpp File Reference
3DOldroydBDesHalfStress.cpp File Reference
Macros
#define EIGEN_USE_BLAS
example with discriptor approach.
#define SIS_USE_LAPACK
Typedefs
typedef complex< double > Cd_t
typedef valarray< double > Vd_t
typedef valarray< complex< double > > Vcd_t
Functions
complex< double > ii (0.0, 1.0)
int main ()
Macro Definition Documentation
EIGEN_USE_BLAS
#define EIGEN_USE_BLAS
example with discriptor approach.
Definition at line 2 of file 3DOldroydBDesHalfStress.cpp.
SIS_USE_LAPACK
#define SIS_USE_LAPACK
Definition at line 3 of file 3DOldroydBDesHalfStress.cpp.
Typedef Documentation
Cd_t
typedef complex<double> Cd_t
Definition at line 10 of file 3DOldroydBDesHalfStress.cpp.
Vcd_t
typedef valarray<complex<double> > Vcd_t
Definition at line 13 of file 3DOldroydBDesHalfStress.cpp.
Vd_t
typedef valarray<double> Vd_t
Definition at line 11 of file 3DOldroydBDesHalfStress.cpp.
Function Documentation
ii()
complex<double> ii (0. 0, 1. 0)
Referenced by main().
main()
int main ()
Definition at line 16 of file 3DOldroydBDesHalfStress.cpp.
References sis::Linop< T >::coef, sis::SingularValueDecomposition< T >::compute(), sis::GeneralizedEigenSolver< T >::eigenvalues, ii(), sis::N, std::pow(), sis::LinopMat< T >::resize(), sis::LinopMat< T >::setConstant(), sis::sis_setup(), and sis::yc().