Spectral Integral Suite in C++: sis::BcMat< std::complex< T > > Class Template Reference
sis::BcMat< std::complex< T > > Class Template Reference
#include <sis.hpp>
Public Member Functions
BcMat ()
BcMat (int m_, int n_)
void resize (int m_, int n_)
void operator= (const BcMat< std::complex< T > > &in)
int rows ()
int cols ()
Eigen::Matrix< std::complex< T >, Eigen::Dynamic, Eigen::Dynamic > operator() (int i, int j, int ord)
Calling BcMat(i,j, ord) will produce row vector representing [---—][a0 a1 ... an C0 C1]^T, assuming ord = 2. i and j refers to an element in the LinopMat L. Suppose L(1,1) is Dyy, and eval(1,1) = -1, then the row matrix will represent the evaluation of that condition in the basis of a0 to C1.
BcMat ()
BcMat (int m_, int n_)
void resize (int m_, int n_)
void operator= (const BcMat< std::complex< T > > &in)
int rows ()
int cols ()
Eigen::Matrix< std::complex< T >, Eigen::Dynamic, Eigen::Dynamic > operator() (int i, int j, int ord)
Calling BcMat(i,j, ord) will produce row vector representing [---—][a0 a1 ... an C0 C1]^T, assuming ord = 2. i and j refers to an element in the LinopMat L. Suppose L(1,1) is Dyy, and eval(1,1) = -1, then the row matrix will represent the evaluation of that condition in the basis of a0 to C1.
Public Attributes
LinopMat< std::complex< T > > L
Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > eval
Eigen::Matrix< std::complex< T >, Eigen::Dynamic, Eigen::Dynamic > vals
Detailed Description
template<class T>
class sis::BcMat< std::complex< T > >
Definition at line 8918 of file sis.hpp.
Constructor & Destructor Documentation
BcMat() [1/4]
template<class T > sis::BcMat< std::complex< T > >::BcMat () inline
Definition at line 8935 of file sis.hpp.
BcMat() [2/4]
template<class T > sis::BcMat< std::complex< T > >::BcMat (int m_, int n_) inline
Definition at line 8939 of file sis.hpp.
References sis::BcMat< T >::eval, sis::BcMat< T >::L, and sis::BcMat< T >::vals.
BcMat() [3/4]
template<class T > sis::BcMat< std::complex< T > >::BcMat () inline
Definition at line 8935 of file sis.hpp.
BcMat() [4/4]
template<class T > sis::BcMat< std::complex< T > >::BcMat (int m_, int n_) inline
Definition at line 8939 of file sis.hpp.
References sis::BcMat< T >::eval, sis::BcMat< T >::L, and sis::BcMat< T >::vals.
Member Function Documentation
cols() [1/2]
template<class T > int sis::BcMat< std::complex< T > >::cols () inline
Definition at line 8969 of file sis.hpp.
cols() [2/2]
template<class T > int sis::BcMat< std::complex< T > >::cols () inline
Definition at line 8969 of file sis.hpp.
operator()() [1/2]
template<class T > Eigen::Matrix<std::complex<T>, Eigen::Dynamic, Eigen::Dynamic> sis::BcMat< std::complex< T > >::operator() (int i, int j, int ord) inline
Calling BcMat(i,j, ord) will produce row vector representing [---—][a0 a1 ... an C0 C1]^T, assuming ord = 2. i and j refers to an element in the LinopMat L. Suppose L(1,1) is Dyy, and eval(1,1) = -1, then the row matrix will represent the evaluation of that condition in the basis of a0 to C1.
Definition at line 8979 of file sis.hpp.
References sis::MatGen< T >::compute(), sis::MatGen< T >::con_mats, sis::BcMat< T >::eval, sis::BcMat< T >::L, sis::MatGen< T >::mats, sis::N, jemdoc::out(), and sis::BcMat< T >::vals.
operator()() [2/2]
template<class T > Eigen::Matrix<std::complex<T>, Eigen::Dynamic, Eigen::Dynamic> sis::BcMat< std::complex< T > >::operator() (int i, int j, int ord) inline
Calling BcMat(i,j, ord) will produce row vector representing [---—][a0 a1 ... an C0 C1]^T, assuming ord = 2. i and j refers to an element in the LinopMat L. Suppose L(1,1) is Dyy, and eval(1,1) = -1, then the row matrix will represent the evaluation of that condition in the basis of a0 to C1.
Definition at line 8979 of file sis.hpp.
References sis::BcMat< T >::eval, sis::BcMat< T >::L, sis::N, jemdoc::out(), and sis::BcMat< T >::vals.
operator=() [1/2]
template<class T > void sis::BcMat< std::complex< T > >::operator= (const BcMat< std::complex< T > > & in) inline
Definition at line 8957 of file sis.hpp.
References sis::BcMat< T >::eval, sis::BcMat< T >::L, and sis::BcMat< T >::vals.
operator=() [2/2]
template<class T > void sis::BcMat< std::complex< T > >::operator= (const BcMat< std::complex< T > > & in) inline
Definition at line 8957 of file sis.hpp.
References sis::BcMat< T >::eval, sis::BcMat< T >::L, and sis::BcMat< T >::vals.
resize() [1/2]
template<class T > void sis::BcMat< std::complex< T > >::resize (int m_, int n_) inline
Definition at line 8948 of file sis.hpp.
References sis::BcMat< T >::eval, sis::BcMat< T >::L, and sis::BcMat< T >::vals.
resize() [2/2]
template<class T > void sis::BcMat< std::complex< T > >::resize (int m_, int n_) inline
Definition at line 8948 of file sis.hpp.
References sis::BcMat< T >::eval, sis::BcMat< T >::L, and sis::BcMat< T >::vals.
rows() [1/2]
template<class T > int sis::BcMat< std::complex< T > >::rows () inline
Definition at line 8965 of file sis.hpp.
rows() [2/2]
template<class T > int sis::BcMat< std::complex< T > >::rows () inline
Definition at line 8965 of file sis.hpp.
Member Data Documentation
eval
template<class T > Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > sis::BcMat< std::complex< T > >::eval
Definition at line 8933 of file sis.hpp.
L
template<class T > LinopMat< std::complex< T > > sis::BcMat< std::complex< T > >::L
Definition at line 8932 of file sis.hpp.
vals
template<class T > Eigen::Matrix< std::complex< T >, Eigen::Dynamic, Eigen::Dynamic > sis::BcMat< std::complex< T > >::vals
Definition at line 8934 of file sis.hpp.
The documentation for this class was generated from the following file:
includes/sis.hpp