Spectral Integral Suite in C++: sis::MatGen< T > Class Template Reference
sis::MatGen< T > Class Template Reference
This class sets up integration Matrices. This class must be intiated by the highest order of based on which integration matrices will be made.
#include <sis.hpp>
Public Member Functions
MatGen ()
Null Constructor.
MatGen (int n_)
Constructor.
void compute (int n_)
Call this to generate integration matrices for highest order n.
void clear ()
MatGen ()
Null Constructor.
MatGen (int n_)
Constructor.
void compute (int n_)
Call this to generate integration matrices for highest order n.
void clear ()
Public Attributes
std::vector< Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > > mats
std::vector< Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > > mats2
std::vector< Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > > con_mats
Detailed Description
template<class T>
class sis::MatGen< T >
This class sets up integration Matrices. This class must be intiated by the highest order of based on which integration matrices will be made.
Definition at line 530 of file sis.hpp.
Constructor & Destructor Documentation
MatGen() [1/4]
template<class T> sis::MatGen< T >::MatGen () inline
Null Constructor.
Definition at line 7966 of file sis.hpp.
MatGen() [2/4]
template<class T> sis::MatGen< T >::MatGen (int n_) inline
Constructor.
Definition at line 7968 of file sis.hpp.
References sis::MatGen< T >::compute().
MatGen() [3/4]
template<class T> sis::MatGen< T >::MatGen () inline
Null Constructor.
Definition at line 7966 of file sis.hpp.
MatGen() [4/4]
template<class T> sis::MatGen< T >::MatGen (int n_) inline
Constructor.
Definition at line 7968 of file sis.hpp.
References sis::MatGen< T >::compute().
Member Function Documentation
clear() [1/2]
template<class T> void sis::MatGen< T >::clear () inline
Definition at line 8019 of file sis.hpp.
References sis::MatGen< T >::con_mats, sis::MatGen< T >::mats, and sis::MatGen< T >::mats2.
Referenced by sis::MatGen< T >::compute(), and sis::MatGen< std::complex< T > >::compute().
clear() [2/2]
template<class T> void sis::MatGen< T >::clear () inline
Definition at line 8019 of file sis.hpp.
References sis::MatGen< T >::con_mats, sis::MatGen< T >::mats, and sis::MatGen< T >::mats2.
compute() [1/2]
template<class T> void sis::MatGen< T >::compute (int n_) inline
Call this to generate integration matrices for highest order n.
Definition at line 7971 of file sis.hpp.
References sis::MatGen< T >::clear(), sis::MatGen< T >::con_mats, sis::MatGen< T >::mats, sis::MatGen< T >::mats2, and sis::N.
compute() [2/2]
template<class T> void sis::MatGen< T >::compute (int n_) inline
Call this to generate integration matrices for highest order n.
Definition at line 7971 of file sis.hpp.
References sis::MatGen< T >::clear(), sis::MatGen< T >::con_mats, sis::MatGen< T >::mats, sis::MatGen< T >::mats2, and sis::N.
Referenced by sis::GeneralizedEigenSolver< T >::compute(), sis::GeneralizedEigenSolver< std::complex< T > >::compute(), sis::GeneralizedEigenSolver< T >::compute_with_constraints(), sis::GeneralizedEigenSolver< std::complex< T > >::computeAppend(), sis::linSolve(), sis::Discretize< std::complex< T > >::MatAppend(), sis::MatGen< T >::MatGen(), sis::MatGen< std::complex< T > >::MatGen(), sis::BcMat< T >::operator()(), sis::BcMat< std::complex< T > >::operator()(), sis::Discretize< T >::operator()(), and sis::Discretize< std::complex< T > >::operator()().
Member Data Documentation
con_mats
template<class T> std::vector< Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > > sis::MatGen< T >::con_mats
Definition at line 7963 of file sis.hpp.
Referenced by sis::MatGen< T >::clear(), sis::MatGen< std::complex< T > >::clear(), sis::MatGen< T >::compute(), sis::MatGen< std::complex< T > >::compute(), sis::GeneralizedEigenSolver< T >::compute_with_constraints(), sis::BcMat< T >::operator()(), and sis::BcMat< std::complex< T > >::operator()().
mats
template<class T> std::vector< Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > > sis::MatGen< T >::mats
Definition at line 7959 of file sis.hpp.
Referenced by sis::MatGen< T >::clear(), sis::MatGen< std::complex< T > >::clear(), sis::MatGen< T >::compute(), sis::MatGen< std::complex< T > >::compute(), sis::GeneralizedEigenSolver< T >::compute_with_constraints(), sis::BcMat< T >::operator()(), and sis::BcMat< std::complex< T > >::operator()().
mats2
template<class T> std::vector< Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > > sis::MatGen< T >::mats2
Definition at line 7961 of file sis.hpp.
Referenced by sis::MatGen< T >::clear(), sis::MatGen< std::complex< T > >::clear(), sis::GeneralizedEigenSolver< T >::compute(), sis::GeneralizedEigenSolver< std::complex< T > >::compute(), sis::MatGen< T >::compute(), sis::MatGen< std::complex< T > >::compute(), sis::GeneralizedEigenSolver< T >::compute_with_constraints(), sis::GeneralizedEigenSolver< std::complex< T > >::computeAppend(), sis::linSolve(), sis::Discretize< std::complex< T > >::MatAppend(), and sis::Discretize< std::complex< T > >::operator()().
The documentation for this class was generated from the following file:
includes/sis.hpp