Spectral Integral Suite in C++: sis::LinopMat< std::complex< T > > Class Template Reference
sis::LinopMat< std::complex< T > > Class Template Reference
This class represents a block matrix operator. It is a matrix of operators.
#include <sis.hpp>
Public Member Functions
LinopMat ()
Null constructor.
LinopMat (int r_, int c_)
Initializes a Linop Matrix of r_ rows and c_ columns.
LinopMat (const LinopMat< std::complex< T > > &in)
Copy constructor.
LinopMat (const LinopMat< T > &in)
Copy constructor.
void operator= (const LinopMat< std::complex< T > > &in)
Assignment operator.
void operator= (const LinopMat< T > &in)
Assignment operator.
LinopMat< std::complex< T > > & operator<< (std::complex< T > b)
Use this to input multiple Linops to the LinopMat using comma separators. Input type of constant.
LinopMat< std::complex< T > > & operator<< (T b)
Use this to input multiple Linops to the LinopMat using comma separators. Input type of constant.
Linop< std::complex< T > > & operator[] (int i)
Use this to to refer to Linops. For 1D Matrices, we use the Row major format when refering to [i]. See wiki for row-major format.
Linop< std::complex< T > > & operator() (int i, int j)
Use this to to refer to Linop. For 2D Matrices, refer to matrix element Linop by (i,j) with the row and column index. Indices start from 0.
ChebfunMat< std::complex< T > > operator() (ChebfunMat< std::complex< T > > in)
Use this to apply a LinopMat on a ChebfunMat.
LinopMat< std::complex< T > > & operator<< (Eigen::Array< std::complex< T >, Eigen::Dynamic, 1 > b)
Use this to input multiple Linops to the LinopMat using comma separators. Input type Eigen array.
LinopMat< std::complex< T > > & operator<< (std::valarray< std::complex< T > > b)
Use this to input multiple Linops to the LinopMat using comma separators. Input type valarray.
LinopMat< std::complex< T > > & operator<< (std::valarray< T > b)
Use this to input multiple Linops to the LinopMat using comma separators. Input type valarray.
LinopMat< std::complex< T > > & operator<< (Linop< std::complex< T > > b)
Use this to input multiple Linops to the LinopMat using comma.
LinopMat< std::complex< T > > & operator<< (Linop< T > b)
Use this to input multiple Linops to the LinopMat using comma.
void resize (int r_, int c_)
This clears all contents in the LinopMat, and then creates a fresh LinopMat of size r_ x c_.
LinopMat< std::complex< T > > & operator, (std::complex< T > b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type constant.
LinopMat< std::complex< T > > & operator, (T b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type constant.
LinopMat< std::complex< T > > & operator, (Eigen::Array< std::complex< T >, Eigen::Dynamic, 1 > b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type Eigen array.
LinopMat< std::complex< T > > & operator, (std::valarray< std::complex< T > > b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type valarray.
LinopMat< std::complex< T > > & operator, (std::valarray< T > b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type valarray.
LinopMat< std::complex< T > > & operator, (Linop< std::complex< T > > b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type Chebfun.
LinopMat< std::complex< T > > & operator, (Linop< T > b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type Chebfun.
void setConstant (T in)
Sets every member in LinopMat to constant.
void setConstant (std::complex< T > in)
Sets every member in LinopMat to complex constant.
void setIdentity ()
Sets LinopMat to identity.
LinopMat< std::complex< T > > & operator<< (LinopMat< std::complex< T > > b)
Use this to input multiple LinopMats to the LinopMat using comma separators. Call at after initializing a LinopMat, or after calling resize, , similar to Eigen's << operator. CAREFUL: If dimensions are not compatible, it will not throw an error, and could end up in segv.
LinopMat< std::complex< T > > & operator, (LinopMat< std::complex< T > > b)
LinopMat< std::complex< T > > & operator<< (LinopMat< T > b)
LinopMat< std::complex< T > > & operator, (LinopMat< T > b)
LinopMat< std::complex< T > > cTranspose ()
Public Attributes
int r
Number of rows.
int c
Number of columns.
std::valarray< Linop< std::complex< T > > > LinopVec
This 1D vector of Linops holds all Linops of the LinopMat in the row-major format.
int countc
int countr
bool go_to_next_row
Detailed Description
template<class T>
class sis::LinopMat< std::complex< T > >
This class represents a block matrix operator. It is a matrix of operators.
Definition at line 8371 of file sis.hpp.
Constructor & Destructor Documentation
LinopMat() [1/4]
template<class T > sis::LinopMat< std::complex< T > >::LinopMat () inline
Null constructor.
Definition at line 8393 of file sis.hpp.
LinopMat() [2/4]
template<class T > sis::LinopMat< std::complex< T > >::LinopMat (int r_, int c_) inline
Initializes a Linop Matrix of r_ rows and c_ columns.
Definition at line 8396 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::LinopVec, and sis::LinopMat< T >::r.
LinopMat() [3/4]
template<class T > sis::LinopMat< std::complex< T > >::LinopMat (const LinopMat< std::complex< T > > & in) inline
Copy constructor.
Definition at line 8404 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::LinopVec, sis::LinopMat< T >::r, and sis::LinopMat< T >::resize().
LinopMat() [4/4]
template<class T > sis::LinopMat< std::complex< T > >::LinopMat (const LinopMat< T > & in) inline
Copy constructor.
Definition at line 8415 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::LinopVec, sis::LinopMat< T >::r, and sis::LinopMat< T >::resize().
Member Function Documentation
cTranspose()
template<class T > LinopMat<std::complex<T> > sis::LinopMat< std::complex< T > >::cTranspose () inline
Definition at line 8788 of file sis.hpp.
References sis::LinopMat< T >::c, sis::conj(), and sis::LinopMat< T >::r.
operator()() [1/2]
template<class T > Linop<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator() (int i, int j) inline
Use this to to refer to Linop. For 2D Matrices, refer to matrix element Linop by (i,j) with the row and column index. Indices start from 0.
Definition at line 8469 of file sis.hpp.
References sis::LinopMat< T >::c, and sis::LinopMat< T >::LinopVec.
operator()() [2/2]
template<class T > ChebfunMat<std::complex<T> > sis::LinopMat< std::complex< T > >::operator() (ChebfunMat< std::complex< T > > in) inline
Use this to apply a LinopMat on a ChebfunMat.
Definition at line 8475 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::LinopMat< T >::c, sis::LinopMat< T >::operator()(), sis::ChebfunMat< T >::r, and sis::LinopMat< T >::r.
operator,() [1/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator, (std::complex< T > b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type constant.
Definition at line 8551 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator,() [2/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator, (T b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type constant.
Definition at line 8559 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator,() [3/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator, (Eigen::Array< std::complex< T >, Eigen::Dynamic, 1 > b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type Eigen array.
Definition at line 8567 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator,() [4/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator, (std::valarray< std::complex< T > > b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type valarray.
Definition at line 8576 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator,() [5/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator, (std::valarray< T > b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type valarray.
Definition at line 8583 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator,() [6/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator, (Linop< std::complex< T > > b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type Chebfun.
Definition at line 8591 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator,() [7/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator, (Linop< T > b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type Chebfun.
Definition at line 8599 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator,() [8/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator, (LinopMat< std::complex< T > > b) inline
Definition at line 8670 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::countc, sis::LinopMat< T >::countr, sis::LinopMat< T >::go_to_next_row, and sis::LinopMat< T >::operator()().
operator,() [9/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator, (LinopMat< T > b) inline
Definition at line 8745 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::countc, sis::LinopMat< T >::countr, sis::LinopMat< T >::go_to_next_row, and sis::LinopMat< T >::operator()().
operator<<() [1/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator<< (T b) inline
Use this to input multiple Linops to the LinopMat using comma separators. Input type of constant.
Definition at line 8455 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator<<() [2/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator<< (std::complex< T > b) inline
Use this to input multiple Linops to the LinopMat using comma separators. Input type of constant.
Definition at line 8447 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator<<() [3/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator<< (Eigen::Array< std::complex< T >, Eigen::Dynamic, 1 > b) inline
Use this to input multiple Linops to the LinopMat using comma separators. Input type Eigen array.
Definition at line 8500 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator<<() [4/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator<< (std::valarray< std::complex< T > > b) inline
Use this to input multiple Linops to the LinopMat using comma separators. Input type valarray.
Definition at line 8509 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator<<() [5/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator<< (std::valarray< T > b) inline
Use this to input multiple Linops to the LinopMat using comma separators. Input type valarray.
Definition at line 8517 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator<<() [6/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator<< (Linop< std::complex< T > > b) inline
Use this to input multiple Linops to the LinopMat using comma.
Definition at line 8525 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator<<() [7/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator<< (Linop< T > b) inline
Use this to input multiple Linops to the LinopMat using comma.
Definition at line 8533 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
operator<<() [8/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator<< (LinopMat< std::complex< T > > b) inline
Use this to input multiple LinopMats to the LinopMat using comma separators. Call at after initializing a LinopMat, or after calling resize, , similar to Eigen's << operator. CAREFUL: If dimensions are not compatible, it will not throw an error, and could end up in segv.
Definition at line 8638 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::countc, sis::LinopMat< T >::countr, sis::LinopMat< T >::go_to_next_row, sis::LinopMat< T >::operator()(), sis::LinopMat< T >::r, and sis::LinopMat< T >::setConstant().
operator<<() [9/9]
template<class T > LinopMat<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator<< (LinopMat< T > b) inline
Definition at line 8714 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::countc, sis::LinopMat< T >::countr, sis::LinopMat< T >::go_to_next_row, sis::LinopMat< T >::operator()(), sis::LinopMat< T >::r, and sis::LinopMat< T >::setConstant().
operator=() [1/2]
template<class T > void sis::LinopMat< std::complex< T > >::operator= (const LinopMat< std::complex< T > > & in) inline
Assignment operator.
Definition at line 8425 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::LinopVec, sis::LinopMat< T >::r, and sis::LinopMat< T >::resize().
operator=() [2/2]
template<class T > void sis::LinopMat< std::complex< T > >::operator= (const LinopMat< T > & in) inline
Assignment operator.
Definition at line 8436 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::LinopVec, sis::LinopMat< T >::r, and sis::LinopMat< T >::resize().
operator[]()
template<class T > Linop<std::complex<T> >& sis::LinopMat< std::complex< T > >::operator[] (int i) inline
Use this to to refer to Linops. For 1D Matrices, we use the Row major format when refering to [i]. See wiki for row-major format.
Definition at line 8464 of file sis.hpp.
References sis::LinopMat< T >::LinopVec.
resize()
template<class T > void sis::LinopMat< std::complex< T > >::resize (int r_, int c_) inline
This clears all contents in the LinopMat, and then creates a fresh LinopMat of size r_ x c_.
Definition at line 8542 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::LinopVec, and sis::LinopMat< T >::r.
setConstant() [1/2]
template<class T > void sis::LinopMat< std::complex< T > >::setConstant (T in) inline
Sets every member in LinopMat to constant.
Definition at line 8606 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::operator()(), and sis::LinopMat< T >::r.
setConstant() [2/2]
template<class T > void sis::LinopMat< std::complex< T > >::setConstant (std::complex< T > in) inline
Sets every member in LinopMat to complex constant.
Definition at line 8615 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::operator()(), and sis::LinopMat< T >::r.
setIdentity()
template<class T > void sis::LinopMat< std::complex< T > >::setIdentity () inline
Sets LinopMat to identity.
Definition at line 8624 of file sis.hpp.
References sis::LinopMat< T >::c, sis::LinopMat< T >::operator()(), sis::LinopMat< T >::r, and sis::LinopMat< T >::setConstant().
Member Data Documentation
c
template<class T > int sis::LinopMat< std::complex< T > >::c
Number of columns.
Definition at line 8383 of file sis.hpp.
countc
template<class T > int sis::LinopMat< std::complex< T > >::countc
Definition at line 8388 of file sis.hpp.
countr
template<class T > int sis::LinopMat< std::complex< T > >::countr
Definition at line 8389 of file sis.hpp.
go_to_next_row
template<class T > bool sis::LinopMat< std::complex< T > >::go_to_next_row
Definition at line 8390 of file sis.hpp.
LinopVec
template<class T > std::valarray<Linop<std::complex<T> > > sis::LinopMat< std::complex< T > >::LinopVec
This 1D vector of Linops holds all Linops of the LinopMat in the row-major format.
Definition at line 8386 of file sis.hpp.
r
template<class T > int sis::LinopMat< std::complex< T > >::r
Number of rows.
Definition at line 8381 of file sis.hpp.
The documentation for this class was generated from the following file:
includes/sis.hpp