Spectral Integral Suite in C++: sis::ChebfunMat< T > Class Template Reference
sis::ChebfunMat< T > Class Template Reference
This class holds a matrix of Chebfuns.
#include <sis.hpp>
Public Member Functions
ChebfunMat ()
Null constructor.
ChebfunMat (int r_, int c_)
Initializes a Chebfun Matrix of r_ rows and c_ columns.
ChebfunMat (const ChebfunMat< T > &in)
Copy constructor.
void operator= (const ChebfunMat &in)
Assignment operator.
void operator= (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > &in)
Assigning a ChebfunMat using a Eigen-matrix. Eigen-Matrix should be of size (r*(N+1), c), else an error is thrown. This implies that one must have called the resize(r,c) function before using this.
ChebfunMat< T > & operator<< (T b)
Use this to input multiple Chebfuns to the ChebfunMat using comma separators. Input type of constant.
Chebfun< T > & operator[] (int i)
Use this to to refer to Chebfuns. For 1D Matrices, we use the Row major format when refering to [i]. See wiki for row-major format.
Chebfun< T > & operator() (int i, int j)
Use this to to refer to Chebfuns. For 2D Matrices, refer to matrix element Chebfun by (i,j) with the row and column index. Indices start from 0.
void p2c ()
Converts every element to Cheb-space, if not already in Cheb-space.
void c2p ()
Converts every element to phys-space, if not already in phys-space.
Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > operator() (T p)
Use this to evaluate the whole ChebfunMat at a given point. Point must lie in the domain, [-1,1].
ChebfunMat< T > & operator<< (Eigen::Array< T, Eigen::Dynamic, 1 > b)
Use this to input multiple Chebfuns to the ChebfunMat using comma separators. Input type Eigen array.
ChebfunMat< T > & operator<< (std::valarray< T > b)
Use this to input multiple Chebfuns to the ChebfunMat using comma separators. Input type valarray.
ChebfunMat< T > & operator<< (Chebfun< T > b)
Use this to input multiple Chebfuns to the ChebfunMat using comma.
void resize (int r_, int c_)
This clears all contents in the ChebfunMat, and then creates a fresh ChebfunMat of size r_ x c_.
ChebfunMat< T > & operator, (T b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type constant.
ChebfunMat< T > & operator, (Eigen::Array< T, Eigen::Dynamic, 1 > b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type Eigen array.
ChebfunMat< T > & operator, (std::valarray< T > b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type valarray.
ChebfunMat< T > & operator, (Chebfun< T > b)
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type Chebfun.
void setConstant (double in)
sets the all the Chebfuns in the ChebfunMat to constant
ChebfunMat< T > cTranspose ()
Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > ChebfunMat2EigenMat ()
Returns an Eigen matrix representing the ChebfunMat.
Public Attributes
int r
Number of rows.
int c
Number of columns.
std::valarray< Chebfun< T > > ChebfunVec
This 1D vector of Chebfuns holds all Chebfuns of the ChebfunMat in the row-major format.
Detailed Description
template<class T>
class sis::ChebfunMat< T >
This class holds a matrix of Chebfuns.
Definition at line 2002 of file sis.hpp.
Constructor & Destructor Documentation
ChebfunMat() [1/3]
template<class T> sis::ChebfunMat< T >::ChebfunMat () inline
Null constructor.
Definition at line 2018 of file sis.hpp.
ChebfunMat() [2/3]
template<class T> sis::ChebfunMat< T >::ChebfunMat (int r_, int c_) inline
Initializes a Chebfun Matrix of r_ rows and c_ columns.
Definition at line 2021 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::ChebfunMat< T >::ChebfunVec, and sis::ChebfunMat< T >::r.
ChebfunMat() [3/3]
template<class T> sis::ChebfunMat< T >::ChebfunMat (const ChebfunMat< T > & in) inline
Copy constructor.
Definition at line 2029 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::ChebfunMat< T >::ChebfunVec, sis::ChebfunMat< T >::r, and sis::ChebfunMat< T >::resize().
Member Function Documentation
c2p()
template<class T> void sis::ChebfunMat< T >::c2p () inline
Converts every element to phys-space, if not already in phys-space.
Definition at line 2102 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::ChebfunMat< T >::operator()(), sis::ChebfunMat< T >::r, and SIS_CHEB_SPACE.
Referenced by sis::GeneralizedEigenSolver< std::complex< T > >::compute(), and sis::linSolve().
ChebfunMat2EigenMat()
template<class T> Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic> sis::ChebfunMat< T >::ChebfunMat2EigenMat () inline
Returns an Eigen matrix representing the ChebfunMat.
Definition at line 2225 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::N, sis::ChebfunMat< T >::operator()(), sis::ChebfunMat< T >::r, and SIS_CHEB_SPACE.
Referenced by sis::linSolve().
cTranspose()
template<class T> ChebfunMat<T> sis::ChebfunMat< T >::cTranspose () inline
Definition at line 2212 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::conj(), sis::ChebfunMat< T >::r, and sis::ChebfunMat< T >::resize().
operator()() [1/2]
template<class T> Chebfun<T>& sis::ChebfunMat< T >::operator() (int i, int j) inline
Use this to to refer to Chebfuns. For 2D Matrices, refer to matrix element Chebfun by (i,j) with the row and column index. Indices start from 0.
Definition at line 2088 of file sis.hpp.
References sis::ChebfunMat< T >::c, and sis::ChebfunMat< T >::ChebfunVec.
Referenced by sis::ChebfunMat< T >::c2p(), sis::ChebfunMat< std::complex< T > >::c2p(), sis::ChebfunMat< T >::ChebfunMat2EigenMat(), sis::ChebfunMat< std::complex< T > >::ChebfunMat2EigenMat(), sis::ChebfunMat< T >::operator()(), sis::ChebfunMat< std::complex< T > >::operator()(), sis::ChebfunMat< T >::operator=(), sis::ChebfunMat< std::complex< T > >::operator=(), sis::ChebfunMat< T >::p2c(), sis::ChebfunMat< std::complex< T > >::p2c(), sis::ChebfunMat< T >::setConstant(), and sis::ChebfunMat< std::complex< T > >::setConstant().
operator()() [2/2]
template<class T> Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic > sis::ChebfunMat< T >::operator() (T p) inline
Use this to evaluate the whole ChebfunMat at a given point. Point must lie in the domain, [-1,1].
Definition at line 2116 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::ChebfunMat< T >::operator()(), and sis::ChebfunMat< T >::r.
operator,() [1/4]
template<class T> ChebfunMat<T>& sis::ChebfunMat< T >::operator, (T b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type constant.
Definition at line 2173 of file sis.hpp.
References sis::ChebfunMat< T >::ChebfunVec.
operator,() [2/4]
template<class T> ChebfunMat<T>& sis::ChebfunMat< T >::operator, (Eigen::Array< T, Eigen::Dynamic, 1 > b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type Eigen array.
Definition at line 2180 of file sis.hpp.
References sis::ChebfunMat< T >::ChebfunVec, and sis::N.
operator,() [3/4]
template<class T> ChebfunMat<T>& sis::ChebfunMat< T >::operator, (std::valarray< T > b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type valarray.
Definition at line 2190 of file sis.hpp.
References sis::ChebfunMat< T >::ChebfunVec.
operator,() [4/4]
template<class T> ChebfunMat<T>& sis::ChebfunMat< T >::operator, (Chebfun< T > b) inline
Overloads comma separator to input Chebfuns into a ChebfunMat. Input type Chebfun.
Definition at line 2197 of file sis.hpp.
References sis::ChebfunMat< T >::ChebfunVec.
operator<<() [1/4]
template<class T> ChebfunMat<T>& sis::ChebfunMat< T >::operator<< (T b) inline
Use this to input multiple Chebfuns to the ChebfunMat using comma separators. Input type of constant.
Definition at line 2071 of file sis.hpp.
References sis::ChebfunMat< T >::ChebfunVec.
operator<<() [2/4]
template<class T> ChebfunMat<T>& sis::ChebfunMat< T >::operator<< (Chebfun< T > b) inline
Use this to input multiple Chebfuns to the ChebfunMat using comma.
Definition at line 2155 of file sis.hpp.
References sis::ChebfunMat< T >::ChebfunVec.
operator<<() [3/4]
template<class T> ChebfunMat<T>& sis::ChebfunMat< T >::operator<< (Eigen::Array< T, Eigen::Dynamic, 1 > b) inline
Use this to input multiple Chebfuns to the ChebfunMat using comma separators. Input type Eigen array.
Definition at line 2134 of file sis.hpp.
References sis::ChebfunMat< T >::ChebfunVec, and sis::N.
operator<<() [4/4]
template<class T> ChebfunMat<T>& sis::ChebfunMat< T >::operator<< (std::valarray< T > b) inline
Use this to input multiple Chebfuns to the ChebfunMat using comma separators. Input type valarray.
Definition at line 2146 of file sis.hpp.
References sis::ChebfunMat< T >::ChebfunVec.
operator=() [1/2]
template<class T> void sis::ChebfunMat< T >::operator= (const ChebfunMat< T > & in) inline
Assignment operator.
Definition at line 2039 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::ChebfunMat< T >::ChebfunVec, sis::ChebfunMat< T >::r, and sis::ChebfunMat< T >::resize().
operator=() [2/2]
template<class T> void sis::ChebfunMat< T >::operator= (const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > & in) inline
Assigning a ChebfunMat using a Eigen-matrix. Eigen-Matrix should be of size (r*(N+1), c), else an error is thrown. This implies that one must have called the resize(r,c) function before using this.
Definition at line 2053 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::N, sis::ChebfunMat< T >::operator()(), and sis::ChebfunMat< T >::r.
operator[]()
template<class T> Chebfun<T>& sis::ChebfunMat< T >::operator[] (int i) inline
Use this to to refer to Chebfuns. For 1D Matrices, we use the Row major format when refering to [i]. See wiki for row-major format.
Definition at line 2080 of file sis.hpp.
References sis::ChebfunMat< T >::ChebfunVec.
p2c()
template<class T> void sis::ChebfunMat< T >::p2c () inline
Converts every element to Cheb-space, if not already in Cheb-space.
Definition at line 2091 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::ChebfunMat< T >::operator()(), sis::ChebfunMat< T >::r, and SIS_PHYS_SPACE.
resize()
template<class T> void sis::ChebfunMat< T >::resize (int r_, int c_) inline
This clears all contents in the ChebfunMat, and then creates a fresh ChebfunMat of size r_ x c_.
Definition at line 2164 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::ChebfunMat< T >::ChebfunVec, and sis::ChebfunMat< T >::r.
Referenced by sis::ChebfunMat< T >::ChebfunMat(), sis::ChebfunMat< std::complex< T > >::ChebfunMat(), sis::EigenSorter< T >::compute(), sis::GeneralizedEigenSolver< std::complex< T > >::compute(), sis::conj(), sis::ChebfunMat< T >::cTranspose(), sis::ChebfunMat< std::complex< T > >::cTranspose(), sis::diff(), sis::GeneralizedEigenSolver< std::complex< T > >::keep(), sis::GeneralizedEigenSolver< std::complex< T > >::keepConverged(), sis::operator*(), sis::operator+(), sis::ChebfunMat< T >::operator=(), sis::ChebfunMat< std::complex< T > >::operator=(), and sis::GeneralizedEigenSolver< std::complex< T > >::removeInf().
setConstant()
template<class T> void sis::ChebfunMat< T >::setConstant (double in) inline
sets the all the Chebfuns in the ChebfunMat to constant
Definition at line 2204 of file sis.hpp.
References sis::ChebfunMat< T >::c, sis::ChebfunMat< T >::operator()(), and sis::ChebfunMat< T >::r.
Member Data Documentation
c
template<class T> int sis::ChebfunMat< T >::c
Number of columns.
Definition at line 2013 of file sis.hpp.
Referenced by sis::ChebfunMat< T >::c2p(), sis::ChebfunMat< std::complex< T > >::c2p(), sis::ChebfunMat< T >::ChebfunMat(), sis::ChebfunMat< std::complex< T > >::ChebfunMat(), sis::ChebfunMat< T >::ChebfunMat2EigenMat(), sis::ChebfunMat< std::complex< T > >::ChebfunMat2EigenMat(), sis::conj(), sis::ChebfunMat< T >::cTranspose(), sis::ChebfunMat< std::complex< T > >::cTranspose(), sis::diff(), sis::GeneralizedEigenSolver< std::complex< T > >::keep(), sis::GeneralizedEigenSolver< std::complex< T > >::keepConverged(), sis::linSolve(), sis::ChebfunMat< T >::operator()(), sis::ChebfunMat< std::complex< T > >::operator()(), sis::LinopMat< std::complex< T > >::operator()(), sis::operator*(), sis::operator+(), sis::ChebfunMat< T >::operator=(), sis::ChebfunMat< std::complex< T > >::operator=(), sis::ChebfunMat< T >::p2c(), sis::ChebfunMat< std::complex< T > >::p2c(), sis::GeneralizedEigenSolver< std::complex< T > >::removeInf(), sis::ChebfunMat< T >::resize(), sis::ChebfunMat< std::complex< T > >::resize(), sis::ChebfunMat< T >::setConstant(), sis::ChebfunMat< std::complex< T > >::setConstant(), and sis::GeneralizedEigenSolver< std::complex< T > >::sortByLargestReal().
ChebfunVec
template<class T> std::valarray<Chebfun<T> > sis::ChebfunMat< T >::ChebfunVec
This 1D vector of Chebfuns holds all Chebfuns of the ChebfunMat in the row-major format.
Definition at line 2016 of file sis.hpp.
Referenced by sis::ChebfunMat< T >::ChebfunMat(), sis::ChebfunMat< std::complex< T > >::ChebfunMat(), sis::ChebfunMat< T >::operator()(), sis::ChebfunMat< std::complex< T > >::operator()(), sis::ChebfunMat< T >::operator,(), sis::ChebfunMat< std::complex< T > >::operator,(), sis::ChebfunMat< T >::operator<<(), sis::ChebfunMat< std::complex< T > >::operator<<(), sis::ChebfunMat< T >::operator=(), sis::ChebfunMat< std::complex< T > >::operator=(), sis::ChebfunMat< T >::operator[](), sis::ChebfunMat< std::complex< T > >::operator[](), sis::ChebfunMat< T >::resize(), and sis::ChebfunMat< std::complex< T > >::resize().
r
template<class T> int sis::ChebfunMat< T >::r
Number of rows.
Definition at line 2011 of file sis.hpp.
Referenced by sis::ChebfunMat< T >::c2p(), sis::ChebfunMat< std::complex< T > >::c2p(), sis::ChebfunMat< T >::ChebfunMat(), sis::ChebfunMat< std::complex< T > >::ChebfunMat(), sis::ChebfunMat< T >::ChebfunMat2EigenMat(), sis::ChebfunMat< std::complex< T > >::ChebfunMat2EigenMat(), sis::conj(), sis::ChebfunMat< T >::cTranspose(), sis::ChebfunMat< std::complex< T > >::cTranspose(), sis::diff(), sis::GeneralizedEigenSolver< std::complex< T > >::keep(), sis::GeneralizedEigenSolver< std::complex< T > >::keepConverged(), sis::linSolve(), sis::ChebfunMat< T >::operator()(), sis::ChebfunMat< std::complex< T > >::operator()(), sis::LinopMat< std::complex< T > >::operator()(), sis::operator*(), sis::operator+(), sis::ChebfunMat< T >::operator=(), sis::ChebfunMat< std::complex< T > >::operator=(), sis::ChebfunMat< T >::p2c(), sis::ChebfunMat< std::complex< T > >::p2c(), sis::GeneralizedEigenSolver< std::complex< T > >::removeInf(), sis::ChebfunMat< T >::resize(), sis::ChebfunMat< std::complex< T > >::resize(), sis::ChebfunMat< T >::setConstant(), sis::ChebfunMat< std::complex< T > >::setConstant(), and sis::GeneralizedEigenSolver< std::complex< T > >::sortByLargestReal().
The documentation for this class was generated from the following file:
includes/sis.hpp