Spectral Integral Suite in C++: sis::nChoosek< T > Class Template Reference
sis::nChoosek< T > Class Template Reference
Class to compute binomial coefficients \(\binom{n}{k} \) returns a double output.
#include <sis.hpp>
Public Member Functions
nChoosek ()
T operator() (int n, int k)
int nCk_ (int n, int k)
nChoosek ()
T operator() (int n, int k)
int nCk_ (int n, int k)
Detailed Description
template<class T>
class sis::nChoosek< T >
Class to compute binomial coefficients \(\binom{n}{k} \) returns a double output.
Definition at line 9037 of file sis.hpp.
Constructor & Destructor Documentation
nChoosek() [1/2]
template<class T> sis::nChoosek< T >::nChoosek () inline
Definition at line 9039 of file sis.hpp.
nChoosek() [2/2]
template<class T> sis::nChoosek< T >::nChoosek () inline
Definition at line 9039 of file sis.hpp.
Member Function Documentation
nCk_() [1/2]
template<class T> int sis::nChoosek< T >::nCk_ (int n, int k) inline
Definition at line 9043 of file sis.hpp.
Referenced by sis::nChoosek< T >::nCk_(), sis::nChoosek< std::complex< T > >::nCk_(), sis::nChoosek< T >::operator()(), and sis::nChoosek< std::complex< T > >::operator()().
nCk_() [2/2]
template<class T> int sis::nChoosek< T >::nCk_ (int n, int k) inline
Definition at line 9043 of file sis.hpp.
References sis::nChoosek< T >::nCk_().
operator()() [1/2]
template<class T> T sis::nChoosek< T >::operator() (int n, int k) inline
Definition at line 9041 of file sis.hpp.
References sis::nChoosek< T >::nCk_().
operator()() [2/2]
template<class T> T sis::nChoosek< T >::operator() (int n, int k) inline
Definition at line 9041 of file sis.hpp.
References sis::nChoosek< T >::nCk_().
The documentation for this class was generated from the following file:
includes/sis.hpp