Spectral Integral Suite in C++: examples/Eigenvalues/Ex_08.cpp File Reference
Ex_08.cpp File Reference
Finds eigenvalues for the Orr-Sommerfeld operator.
Detailed Description
Finds eigenvalues for the Orr-Sommerfeld operator.
Solving the Eigenvalue problem:
\[ \left(\frac{1}{Re}\partial_{yyyy} - \left(\frac{2}{Re} + (1-y^2)\,i \right) \partial_{yy} + \left(\frac{1}{Re} -2i + (1-y^2)\,i \right)\right)u \;=\; \lambda \; (\partial_{yy} - 1) u \]
Definition in file Ex_08.cpp.
Typedefs
typedef complex< double > Cd_t
typedef valarray< double > Vd_t
Functions
int main ()
Typedef Documentation
Cd_t
typedef complex<double> Cd_t
Definition at line 17 of file Ex_08.cpp.
Vd_t
typedef valarray<double> Vd_t
Definition at line 18 of file Ex_08.cpp.
Function Documentation
main()
int main ()
Definition at line 20 of file Ex_08.cpp.
References sis::Linop< T >::coef, sis::GeneralizedEigenSolver< T >::compute(), sis::GeneralizedEigenSolver< T >::eigenvalues, sis::BcMat< T >::eval, ii(), sis::BcMat< T >::L, sis::N, std::pow(), sis::sis_setup(), and sis::y().