Spectral Integral Suite in C++: examples/FrequencyResponses/Ex_13.cpp File Reference
Ex_13.cpp File Reference
Solving for the principal singular values of an Oldroyd-B fluid. See Figure 8 in [3].
Detailed Description
Solving for the principal singular values of an Oldroyd-B fluid. See Figure 8 in [3].
Definition in file Ex_13.cpp.
Macros
#define EIGEN_USE_MKL_ALL
#define EIGEN_FAST_MATH 0
Typedefs
typedef complex< double > Cd_t
typedef valarray< double > Vd_t
typedef valarray< complex< double > > Vcd_t
Functions
int main ()
Macro Definition Documentation
EIGEN_FAST_MATH
#define EIGEN_FAST_MATH 0
Definition at line 7 of file Ex_13.cpp.
EIGEN_USE_MKL_ALL
#define EIGEN_USE_MKL_ALL
Definition at line 4 of file Ex_13.cpp.
Typedef Documentation
Cd_t
typedef complex<double> Cd_t
Definition at line 17 of file Ex_13.cpp.
Vcd_t
typedef valarray<complex<double> > Vcd_t
Definition at line 19 of file Ex_13.cpp.
Vd_t
typedef valarray<double> Vd_t
Definition at line 18 of file Ex_13.cpp.
Function Documentation
main()
int main ()
Definition at line 20 of file Ex_13.cpp.
References sis::Linop< T >::coef, sis::SingularValueDecomposition< T >::compute(), sis::GeneralizedEigenSolver< T >::eigenvalues, ii(), sis::N, std::pow(), sis::sis_setup(), and sis::yc().