Spectral Integral Suite in C++: examples/EquationSolving/Ex_02.cpp File Reference
Ex_02.cpp File Reference
An example with a fourth order system.
Detailed Description
An example with a fourth order system.
Solves a fourth order system:
\[ \partial_{yyyy}u(y) \,-\, 4\,\partial_{yy}u(y) \,+\, 8\,u(y) \;= \; 1 \,-\, y^2 \,+\, y^3, \]
with clamped boundary conditions:
\[ \begin{array}{cll} \partial_yu(1) \;&=\; u(1) \;&=\; 0 \\ \partial_yu(-1) \;&=\; u(-1) \;&=\; 0. \end{array} \]
Definition in file Ex_02.cpp.
Typedefs
typedef complex< double > Cd_t
typedef valarray< double > Vd_t
Functions
int main ()
Typedef Documentation
Cd_t
typedef complex<double> Cd_t
Definition at line 26 of file Ex_02.cpp.
Vd_t
typedef valarray<double> Vd_t
Definition at line 27 of file Ex_02.cpp.
Function Documentation
main()
int main ()
Definition at line 29 of file Ex_02.cpp.
References sis::Linop< T >::coef, sis::BcMat< T >::eval, sis::BcMat< T >::L, sis::linSolve(), sis::N, sis::sis_setup(), sis::BcMat< T >::vals, sis::yc(), and sis::yEigen.