Spectral Integral Suite in C++: std Namespace Reference
std Namespace Reference
Functions
template<class T >
std::valarray< std::complex< T > > dou2com (const std::valarray< T > &a, const std::valarray< T > &b)
Use this to make a complex valarray out of two real valarrays.
template<class T >
valarray< T > real (const valarray< complex< T > > &in)
real part of a complex valarray
template<class T >
valarray< T > imag (const valarray< complex< T > > &in)
imaginary part of a complex valarray
template<class T >
std::valarray< std::complex< T > > operator* (std::complex< T > left, std::valarray< T > right)
Multiplying a complex number with a real valarray.
template<class T >
std::valarray< std::complex< T > > operator* (const std::valarray< T > &left, const std::complex< T > &right)
Multiplying a real valarray with a complex number.
template<class T >
std::valarray< std::complex< T > > operator+ (std::complex< T > left, std::valarray< T > right)
Adding a complex number to a real valarray.
template<class T >
std::valarray< std::complex< T > > operator+ (const std::valarray< T > &left, std::complex< T > right)
Multiplying a real valarray with a complex number.
template<class T >
std::valarray< std::complex< T > > operator- (std::complex< T > left, std::valarray< T > right)
Subtracting a real valarray from a complex number.
template<class T >
std::valarray< std::complex< T > > operator- (const std::valarray< T > &left, const std::complex< T > &right)
Subtracting a complex number from a real valarray.
template<class T >
std::valarray< std::complex< T > > operator* (T left, std::valarray< std::complex< T > > right)
template<class T >
std::valarray< std::complex< T > > operator* (const std::valarray< std::complex< T > > &left, const T &right)
Multiplying a real number with a complex valarray.
template<class T >
std::valarray< std::complex< T > > operator+ (T left, std::valarray< std::complex< T > > right)
Adding a complex valarray to a real number.
template<class T >
std::valarray< std::complex< T > > operator+ (const std::valarray< std::complex< T > > &left, const T &right)
Adding a real number with a complex valarray.
template<class T >
std::valarray< std::complex< T > > operator- (T left, std::valarray< std::complex< T > > right)
Subtracting a real number from a complex valarray.
template<class T >
std::valarray< std::complex< T > > operator- (const std::valarray< std::complex< T > > &left, const T &right)
Subtracting a complex valarray from a real number.
template<class T >
std::valarray< std::complex< T > > operator* (const std::valarray< std::complex< T > > &left, const std::valarray< T > &right)
Multiplying a complex valarray to a real valarray:
template<class T >
std::valarray< std::complex< T > > operator* (const std::valarray< T > &left, const std::valarray< std::complex< T > > &right)
Multiplying a real valarray to a complex valarray:
string int2str (int i)
template<class T >
valarray< complex< T > > pow (valarray< complex< T > > base, T power)
Function Documentation
dou2com()
template<class T > std::valarray< std::complex< T > > std::dou2com (const std::valarray< T > & a, const std::valarray< T > & b)
Use this to make a complex valarray out of two real valarrays.
Definition at line 264 of file sis.hpp.
Referenced by operator*(), operator+(), and operator-().
imag()
template<class T > valarray< T > std::imag (const valarray< complex< T > > & in)
imaginary part of a complex valarray
Definition at line 291 of file sis.hpp.
Referenced by sis::Chebfun< std::complex< T > >::c2p(), sis::dct(), sis::dou2com(), sis::Chebfun< std::complex< T > >::evi(), sis::idct(), sis::Chebfun< std::complex< T > >::imag(), sis::Linop< std::complex< T > >::imag(), sis::Chebfun< std::complex< T > >::MultMat(), operator*(), operator+(), sis::operator+(), operator-(), sis::Chebfun< std::complex< T > >::p2c(), and sis::GeneralizedEigenSolver< std::complex< T > >::removeInf().
int2str()
string std::int2str (int i)
Definition at line 445 of file sis.hpp.
References jemdoc::out().
operator*() [1/6]
template<class T > std::valarray< std::complex< T > > std::operator* (std::complex< T > left, std::valarray< T > right)
Multiplying a complex number with a real valarray.
Definition at line 302 of file sis.hpp.
References dou2com(), imag(), and real().
operator*() [2/6]
template<class T > std::valarray< std::complex< T > > std::operator* (const std::valarray< T > & left, const std::complex< T > & right)
Multiplying a real valarray with a complex number.
Definition at line 312 of file sis.hpp.
References dou2com(), imag(), and real().
operator*() [3/6]
template<class T > std::valarray< std::complex< T > > std::operator* (T left, std::valarray< std::complex< T > > right)
Definition at line 367 of file sis.hpp.
References dou2com(), imag(), and real().
operator*() [4/6]
template<class T > std::valarray< std::complex< T > > std::operator* (const std::valarray< std::complex< T > > & left, const T & right)
Multiplying a real number with a complex valarray.
Definition at line 377 of file sis.hpp.
References dou2com(), imag(), and real().
operator*() [5/6]
template<class T > std::valarray< std::complex< T > > std::operator* (const std::valarray< std::complex< T > > & left, const std::valarray< T > & right)
Multiplying a complex valarray to a real valarray:
Definition at line 426 of file sis.hpp.
References dou2com(), imag(), and real().
operator*() [6/6]
template<class T > std::valarray< std::complex< T > > std::operator* (const std::valarray< T > & left, const std::valarray< std::complex< T > > & right)
Multiplying a real valarray to a complex valarray:
Definition at line 437 of file sis.hpp.
References dou2com(), and real().
operator+() [1/4]
template<class T > std::valarray< std::complex< T > > std::operator+ (std::complex< T > left, std::valarray< T > right)
Adding a complex number to a real valarray.
Definition at line 322 of file sis.hpp.
References dou2com(), imag(), and real().
operator+() [2/4]
template<class T > std::valarray< std::complex< T > > std::operator+ (const std::valarray< T > & left, std::complex< T > right)
Multiplying a real valarray with a complex number.
Definition at line 333 of file sis.hpp.
References dou2com(), imag(), and real().
operator+() [3/4]
template<class T > std::valarray< std::complex< T > > std::operator+ (T left, std::valarray< std::complex< T > > right)
Adding a complex valarray to a real number.
Definition at line 387 of file sis.hpp.
References dou2com(), imag(), and real().
operator+() [4/4]
template<class T > std::valarray< std::complex< T > > std::operator+ (const std::valarray< std::complex< T > > & left, const T & right)
Adding a real number with a complex valarray.
Definition at line 397 of file sis.hpp.
References dou2com(), imag(), and real().
operator-() [1/4]
template<class T > std::valarray< std::complex< T > > std::operator- (std::complex< T > left, std::valarray< T > right)
Subtracting a real valarray from a complex number.
Definition at line 344 of file sis.hpp.
References dou2com(), imag(), and real().
operator-() [2/4]
template<class T > std::valarray< std::complex< T > > std::operator- (const std::valarray< T > & left, const std::complex< T > & right)
Subtracting a complex number from a real valarray.
Definition at line 356 of file sis.hpp.
References dou2com(), imag(), and real().
operator-() [3/4]
template<class T > std::valarray< std::complex< T > > std::operator- (T left, std::valarray< std::complex< T > > right)
Subtracting a real number from a complex valarray.
Definition at line 406 of file sis.hpp.
References dou2com(), imag(), and real().
operator-() [4/4]
template<class T > std::valarray< std::complex< T > > std::operator- (const std::valarray< std::complex< T > > & left, const T & right)
Subtracting a complex valarray from a real number.
Definition at line 416 of file sis.hpp.
References dou2com(), imag(), and real().
pow()
template<class T > valarray< complex< T > > std::pow (valarray< complex< T > > base, T power)
Definition at line 453 of file sis.hpp.
References jemdoc::out().
Referenced by intWts(), and main().
real()
template<class T > valarray< T > std::real (const valarray< complex< T > > & in)
real part of a complex valarray
Definition at line 280 of file sis.hpp.
Referenced by sis::Chebfun< std::complex< T > >::c2p(), OrdQz::compute(), sis::GeneralizedEigenSolver< T >::compute(), sis::GeneralizedEigenSolver< std::complex< T > >::compute(), sis::GeneralizedEigenSolver< T >::compute_with_constraints(), sis::GeneralizedEigenSolver< std::complex< T > >::computeAppend(), sis::dct(), dlyap(), sis::dou2com(), sis::Chebfun< std::complex< T > >::evr(), sis::idct(), sis::ifft_cs(), sis::Chebfun< std::complex< T > >::L2norm(), lyap(), main(), sis::Chebfun< std::complex< T > >::MultMat(), operator*(), operator+(), sis::operator+(), operator-(), sis::Chebfun< T >::p2c(), sis::Chebfun< std::complex< T > >::p2c(), sis::Chebfun< std::complex< T > >::real(), sis::Linop< std::complex< T > >::real(), and sis::GeneralizedEigenSolver< std::complex< T > >::removeInf().