Spectral Integral Suite in C++: SISCpp/examples/Eigenvalues/Ex_09.cpp File Reference
Ex_09.cpp File Reference
Macros
#define SIS_USE_LAPACK
Functions
int main ()
Macro Definition Documentation
SIS_USE_LAPACK
#define SIS_USE_LAPACK
Definition at line 70 of file Ex_09.cpp.
Function Documentation
main()
int main ()
Definition at line 77 of file Ex_09.cpp.
References sis::Linop< T >::coef, sis::GeneralizedEigenSolver< T >::compute(), sis::GeneralizedEigenSolver< T >::eigenvalues, sis::BcMat< T >::eval, ii(), ind, sis::BcMat< T >::L, sis::N, sis::Linop< T >::n, std::pow(), sis::LinopMat< T >::resize(), sis::BcMat< T >::resize(), sis::Linop< T >::set(), sis::setChebPts(), sis::sis_setup(), and sis::y().